services:
  db:
    container_name: lalatalk-db
    image: mariadb:10.11
    platform: linux/amd64
    environment:
      MARIADB_ROOT_PASSWORD: Password@12345
      MARIADB_DATABASE: lalatalk_db
      MARIADB_USER: lalatalk_user
      MARIADB_PASSWORD: Password@12345
      TZ: Asia/Tokyo
    ports:
      - 33093:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_init:/docker-entrypoint-initdb.d
    networks:
      - lalatalk-network

  phpmyadmin:
    container_name: lalatalk-phpmyadmin
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=lalatalk-db
      - PMA_USER=lalatalk_user
      - PMA_PASSWORD=Password@12345
    depends_on:
      - db
    ports:
      - 8802:80
    networks:
      - lalatalk-network

  django:
    container_name: lalatalk-django
    build:
      context: ./django
      dockerfile: Dockerfile
    image: lalatalk/django:latest
    platform: linux/amd64
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
      TZ: Asia/Tokyo
    volumes:
      - .:/app
    command: >
      bash -c "
      until nc -z lalatalk-db 3306; do
        echo 'Waiting for the database...';
        sleep 1;
      done;
      python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - lalatalk-network

  nginx:
    container_name: lalatalk-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../app:/var/www/html/app
    depends_on:
      - django
    networks:
      - lalatalk-network

  npm:
    container_name: lalatalk-npm
    image: node:18
    working_dir: /app
    command: "bash -c 'npm install && npm run dev'"
    volumes:
      - .:/app
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    networks:
      - lalatalk-network

  mailhog:
    container_name: lalatalk-mailhog
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - lalatalk-network

networks:
  lalatalk-network:
    driver: bridge